{% set name = "radical.utils" %}
{% set version = "0.50.2" %}
{% set sha256 = "14e4878182f02bcd60d3cfe430b51292aad088fc58e620febd6eb2243a6766d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py3k or win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - future
    - colorama
    - netifaces 0.10.4
    - setproctitle
    
test:
  imports:
    - radical.utils
  
about:
  home: https://github.com/radical-cybertools/radical.utils
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Shared code and tools for various RADICAL Projects (http://radical.rutgers.edu/)'
  description: |
    This Python package contains shared code and tools for various Radical Group projects.
  dev_url: https://github.com/radical-cybertools/radical.utils

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
