{% set name = "radical.utils" %}
{% set version = "1.100.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/radical_utils-{{ version }}.tar.gz
  sha256: c2a09f158db577ac4decc948c5aaf9c7462bbf97ddf692529c40bd4af1d676f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - colorama
    - msgpack-python
    - netifaces
    - ntplib
    - pyzmq
    - regex
    - setproctitle

test:
  imports:
    - radical.utils
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: hhttps://radical-cybertools.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Shared code and tools for various RADICAL-Cybertools projects
  description: |
    This Python package contains shared code and tools for various RADICAL-Cybertools projects.
  dev_url: https://github.com/radical-cybertools/radical.utils
  doc_url: https://radicalutils.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - xylar
