travis:
  secure:
    BINSTAR_TOKEN: rQ23Peb7RMQ7Ygms5y+Le+zzCEYoZiWCuU2RDTONRelcEViAeW9Wf42xSDGCw5CB/WxFaL/5NGjFOXazKunqMbcyU8gTdYSMRJu6o94jc4jQm3uS1yCkYJRTfSPYMa0bNQ4e8BL4SKXSd/Sx8LyVdoNH1Kl5YqQqStHin9knyXSswIXCCAJw6O57P2R54K8mZ4wgjtFFTCAYpSZ74n8EWlAUVtYM44vxNtOuS96NhC2dJuDTRUDQ2ja3TdaI2b82zoL1mldXwYNqcLuCNcteXeyKqjh02V6ZXfOKyHWfktrbE0Nct2mM/So/p68n2CZHUwbSQPRJQwGVqWOdYJ7zTqhItEIqC5meigzWoIriX/4d7BKE8zEsxR3FbZ/SYUw1tYj+TZgkFedY/lrnHfr0ZFTTGUkTLGbHNK5Dpd7F5+DPaJadyRN2UsaSfzjA4WJ5HZaNJ2HzOKpCxcVIjXv1GzMNlF4zLoMdxaLykN4iHLBn/+6dFTTSQrn3McisDJWa+4Qdi+4jzA2dnQYdM/tIczwYqFjhACkYXVzwZyYYw/7hxWqKjF3dLCOutbcgZ+dJVbUGPjZxCNK5rU/5dqmmJk19oA3PtORWEKY5oMspC7DeAJ+ccgZPJWjL8jQub4bu2WW7KQGtue6zUZ8DvjhQJz8iHioM8+igSUw8+YXamb4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: azure
  linux: azure
  linux_aarch64: azure
  linux_ppc64le: azure